/**
 * AI study report — an evidence-backed, exportable synthesis of a survey's
 * simulated responses.
 *
 * Generated by the local agent CLI (operator-side one-shot). Anti-hallucination
 * posture mirrors the theme extraction: the LLM cites question codes and
 * numbered open answers; the server maps citations back to real questionIds /
 * responseIds and DROPS any finding it cannot ground. Themes are reused from
 * the theme cache when present. Caveats (sample size, synthetic provenance,
 * stale themes) are computed server-side — never left to the model.
 *
 * Reports are snapshots: each generation inserts a study_reports row; the UI
 * can re-open any past snapshot and export it as Markdown.
 */
import { and, desc, eq } from "drizzle-orm";
import { db } from "@/db";
import { openTextThemes, questions, responses, studyReports, surveys } from "@/db/schema";
import { computeDistributions } from "@/lib/quality";
import { openAnswerText } from "@/lib/open-answer";
import { runLlmJson } from "@/lib/llm";

export const MIN_RESPONSES_FOR_REPORT = 5;
const MAX_OPEN_ANSWERS_IN_PROMPT = 120;

export interface ReportFinding {
  finding: string;
  action: string;
  /** Grounding: question this finding is about (always present). */
  questionId: string;
  questionPrompt: string;
  /** Response n behind this finding (absent on older snapshots). */
  questionN?: number;
  /** Cited open answers (drill-down to the raw text in the UI). */
  evidence: { responseId: string; text: string }[];
}

export interface ReportThemeSummary {
  questionPrompt: string;
  name: string;
  summary: string;
  count: number;
}

export interface StudyReport {
  title: string;
  overview: string;
  findings: ReportFinding[];
  /** Reused from the US-208 theme cache at generation time. */
  themes: ReportThemeSummary[];
  /** Segment differences the model observed across persona attributes. */
  segmentNotes: string[];
  /** Server-computed + model caveats, always explicit. */
  caveats: string[];
  responseCount: number;
  generatedAt: string;
}

export interface StudyReportRow {
  id: string;
  report: StudyReport;
  responseCount: number;
  createdAt: string;
}

async function ownedSurvey(surveyId: string, workspaceId: string) {
  const [s] = await db
    .select({ id: surveys.id, title: surveys.title, researchGoal: surveys.researchGoal })
    .from(surveys)
    .where(and(eq(surveys.id, surveyId), eq(surveys.workspaceId, workspaceId)))
    .limit(1);
  return s ?? null;
}

export async function listStudyReports(
  surveyId: string,
  workspaceId: string,
): Promise<StudyReportRow[]> {
  if (!(await ownedSurvey(surveyId, workspaceId))) return [];
  const rows = await db
    .select()
    .from(studyReports)
    .where(eq(studyReports.surveyId, surveyId))
    .orderBy(desc(studyReports.createdAt))
    .limit(20);
  return rows.map((r) => ({
    id: r.id,
    report: r.report as StudyReport,
    responseCount: r.responseCount,
    createdAt: r.createdAt.toISOString(),
  }));
}

export async function generateStudyReport(
  surveyId: string,
  workspaceId: string,
): Promise<StudyReportRow> {
  const survey = await ownedSurvey(surveyId, workspaceId);
  if (!survey) throw new Error("설문을 찾을 수 없습니다.");

  const qs = await db
    .select({ id: questions.id, prompt: questions.prompt, type: questions.type, order: questions.order })
    .from(questions)
    .where(eq(questions.surveyId, surveyId))
    .orderBy(questions.order);

  const rows = await db
    .select({ id: responses.id, answers: responses.answers })
    .from(responses)
    .where(and(eq(responses.surveyId, surveyId), eq(responses.isSynthetic, true)));

  if (rows.length < MIN_RESPONSES_FOR_REPORT) {
    throw new Error(
      `리포트 생성에는 시뮬 응답이 최소 ${MIN_RESPONSES_FOR_REPORT}건 필요합니다 (현재 ${rows.length}건).`,
    );
  }

  const distributions = await computeDistributions(surveyId);

  // Numbered open answers (the citation surface for evidence responseIds).
  const openAnswerIndex: { responseId: string; questionId: string; text: string }[] = [];
  for (const q of qs.filter((q) => q.type === "open")) {
    for (const r of rows) {
      const text = openAnswerText((r.answers as Record<string, unknown>)[q.id]).trim();
      if (text) openAnswerIndex.push({ responseId: r.id, questionId: q.id, text });
      if (openAnswerIndex.length >= MAX_OPEN_ANSWERS_IN_PROMPT) break;
    }
  }

  // Reuse cached themes.
  const themeRows = await db
    .select()
    .from(openTextThemes)
    .where(eq(openTextThemes.surveyId, surveyId));
  const promptById = new Map(qs.map((q) => [q.id, q.prompt]));
  const themes: ReportThemeSummary[] = themeRows.flatMap((row) =>
    (Array.isArray(row.themes) ? (row.themes as { name: string; summary: string; responseIds: string[] }[]) : []).map(
      (t) => ({
        questionPrompt: promptById.get(row.questionId) ?? "",
        name: t.name,
        summary: t.summary,
        count: t.responseIds?.length ?? 0,
      }),
    ),
  );

  const qCode = new Map(qs.map((q, i) => [q.id, `Q${i + 1}`]));
  const distBlock = distributions
    .map((d) => {
      const code = qCode.get(d.questionId) ?? "?";
      const top = d.counts
        .slice(0, 6)
        .map((c) => `${c.label} ${c.count}건(${Math.round(c.pct)}%)`)
        .join(", ");
      const extras = [
        d.mean !== undefined ? `평균 ${d.mean.toFixed(1)}` : "",
        d.npsScore !== undefined ? `NPS ${Math.round(d.npsScore)}` : "",
      ]
        .filter(Boolean)
        .join(", ");
      return `${code} [${d.type}] ${d.prompt} — n=${d.n}${top ? ` | ${top}` : ""}${extras ? ` | ${extras}` : ""}`;
    })
    .join("\n");

  const openBlock = openAnswerIndex
    .map((a, i) => `${i + 1}. (${qCode.get(a.questionId)}) ${a.text.slice(0, 300)}`)
    .join("\n");

  const themeBlock = themes.length
    ? themes.map((t) => `- ${t.name} (${t.count}건): ${t.summary}`).join("\n")
    : "(테마 분석 없음)";

  const prompt = `당신은 설문 결과를 이해관계자용 리포트로 종합하는 리서치 분석가입니다. 반드시 아래 데이터에 근거해서만 작성하세요.

설문 제목: "${survey.title ?? ""}"
리서치 목표: "${survey.researchGoal}"
시뮬 응답 수: ${rows.length}건 (합성 데이터 — 실제 응답이 아님)

[문항별 분포]
${distBlock}

[주관식 응답 (번호 인용용)]
${openBlock || "(주관식 응답 없음)"}

[기존 테마 분석]
${themeBlock}

규칙:
- findings는 3~6개. 각 finding은 하나의 문항 코드(questionCode)를 근거로 삼고, 주관식 근거가 있으면 answerNumbers로 번호를 인용할 것.
- 데이터에 없는 수치·주장 금지. 표본이 작으면 단정하지 말 것.
- action은 실행 가능한 한 문장.
- segmentNotes: 채널/이벤트 간 눈에 띄는 차이가 있으면 기술, 없으면 빈 배열.
- caveats: 해석 시 주의점 (데이터 한계 중심).
- 모두 한국어.

Return ONLY a JSON object:
{"title": "...", "overview": "...", "findings": [{"finding": "...", "action": "...", "questionCode": "Q1", "answerNumbers": [1,3]}], "segmentNotes": ["..."], "caveats": ["..."]}`;

  const out = await runLlmJson<{
    title?: unknown;
    overview?: unknown;
    findings?: { finding?: unknown; action?: unknown; questionCode?: unknown; answerNumbers?: unknown }[];
    segmentNotes?: unknown;
    caveats?: unknown;
  }>(prompt);

  const codeToId = new Map([...qCode.entries()].map(([id, code]) => [code, id]));
  const findings: ReportFinding[] = [];
  for (const f of out.findings ?? []) {
    if (typeof f.finding !== "string" || !f.finding.trim()) continue;
    const questionId = typeof f.questionCode === "string" ? codeToId.get(f.questionCode.trim()) : undefined;
    if (!questionId) continue; // ungrounded finding → dropped
    const evidence = (Array.isArray(f.answerNumbers) ? f.answerNumbers : [])
      .map((n) => (typeof n === "number" ? openAnswerIndex[n - 1] : undefined))
      .filter((a): a is (typeof openAnswerIndex)[number] => !!a)
      .map((a) => ({ responseId: a.responseId, text: a.text }));
    findings.push({
      finding: f.finding.trim(),
      action: typeof f.action === "string" ? f.action.trim() : "",
      questionId,
      questionPrompt: promptById.get(questionId) ?? "",
      questionN: distributions.find((d) => d.questionId === questionId)?.n ?? 0,
      evidence,
    });
  }
  if (findings.length === 0) throw new Error("근거 있는 발견을 생성하지 못했습니다 — 다시 시도해 주세요.");

  // Server-side caveats come first — these are facts, not model opinions.
  const staleThemes = themeRows.some((r) => r.responseCount !== rows.length);
  const caveats = [
    "이 리포트는 합성(시뮬레이션) 응답만을 근거로 합니다 — 실제 응답이 아닙니다.",
    `시뮬 응답 ${rows.length}건 기준입니다${rows.length < 30 ? " — 표본이 작아 방향성 참고용입니다" : ""}.`,
    ...(themes.length === 0 ? ["테마 분석이 아직 생성되지 않아 리포트에 포함되지 않았습니다."] : []),
    ...(staleThemes ? ["테마 분석이 최신 응답 수와 달라 재생성이 권장됩니다."] : []),
    ...((Array.isArray(out.caveats) ? out.caveats : []).filter((c): c is string => typeof c === "string")),
  ];

  const report: StudyReport = {
    title: typeof out.title === "string" && out.title.trim() ? out.title.trim() : (survey.title ?? "스터디 리포트"),
    overview: typeof out.overview === "string" ? out.overview.trim() : "",
    findings,
    themes,
    segmentNotes: (Array.isArray(out.segmentNotes) ? out.segmentNotes : []).filter(
      (s): s is string => typeof s === "string",
    ),
    caveats,
    responseCount: rows.length,
    generatedAt: new Date().toISOString(),
  };

  const [row] = await db
    .insert(studyReports)
    .values({
      workspaceId,
      surveyId,
      report,
      responseCount: rows.length,
      model: process.env.LOOP_LLM_MODEL || "sonnet",
    })
    .returning();

  return {
    id: row.id,
    report: row.report as StudyReport,
    responseCount: row.responseCount,
    createdAt: row.createdAt.toISOString(),
  };
}

/** Deterministic Markdown renderer for the export download. */
export function reportToMarkdown(r: StudyReport): string {
  const lines: string[] = [];
  lines.push(`# ${r.title}`);
  lines.push("");
  lines.push(`> 시뮬 응답 ${r.responseCount}건 · 생성 ${r.generatedAt.slice(0, 10)}`);
  lines.push("");
  if (r.overview) {
    lines.push("## 개요");
    lines.push("");
    lines.push(r.overview);
    lines.push("");
  }
  if (r.findings.length) {
    lines.push("## 핵심 발견 & 권장 액션");
    lines.push("");
    r.findings.forEach((f, i) => {
      lines.push(`### ${i + 1}. ${f.finding}`);
      lines.push("");
      lines.push(
        `- 근거 문항: ${f.questionPrompt}${
          typeof f.questionN === "number" && f.questionN > 0
            ? ` (n=${f.questionN}${f.questionN < 30 ? " ⚠︎ 표본 작음" : ""})`
            : ""
        }`,
      );
      if (f.action) lines.push(`- 권장 액션: ${f.action}`);
      if (f.evidence.length) {
        lines.push(`- 근거 응답:`);
        for (const e of f.evidence) lines.push(`  - "${e.text}" (${e.responseId})`);
      }
      lines.push("");
    });
  }
  if (r.themes.length) {
    lines.push("## 주관식 테마");
    lines.push("");
    for (const t of r.themes) lines.push(`- **${t.name}** (${t.count}건) — ${t.summary}`);
    lines.push("");
  }
  if (r.segmentNotes.length) {
    lines.push("## 세그먼트 차이");
    lines.push("");
    for (const s of r.segmentNotes) lines.push(`- ${s}`);
    lines.push("");
  }
  lines.push("## 주의사항");
  lines.push("");
  for (const c of r.caveats) lines.push(`- ${c}`);
  lines.push("");
  return lines.join("\n");
}
